### ISSUE TITLE
Precise code search doesn't work w/o Minio

### ISSUE THREAD

**Issue by eugenberend** [sourcegraph/deploy-sourcegraph-helm#202]
If MinIO disabled, any S3 credentials for precise-code-intel-worker [cannot be specified in the chart](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/9abc264ff36ab0261f3018c395d84df9c692c606/charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml#L60). So in this case pods of precise-code-intel-worker are constantly crashing.
IMO there are not many people which want to use separate MinIO installation for Sourcegraph only.
it should be possible to specify S3 access key ID and secret key that belong to external S3 provider such as any cloud s3-compatible storage.

**Comment by abeatrix** [comment]
@eugenberend Minio must be enabled for precise-code-intel-worker to work properly.

Please see our [docs here](https://docs.sourcegraph.com/admin/external_services/object_storage) if you would like to specify S3 access key ID and secret key that belongs to the external S3 provider.

Hope this helps!
