### ISSUE TITLE
PodSecurityPolices are deprecated

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/deploy-sourcegraph-helm#205]
@sourcegraph/delivery 

Both [cadvisor](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/cadvisor/cadvisor.PodSecurityPolicy.yaml) and node-exporter have [PodSecurityPolicy](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/node-exporter/node-exporter.PodSecurityPolicy.yaml) manifests. 

However, PodSecurityPolicies have been removed entirely from k8s in `v1.25` (released August 2022): https://kubernetes.io/docs/concepts/security/pod-security-policy/. 

We should investigate removing them from our helm chart, and providing an alternative (such as https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/)

**Comment by ggilmore** [comment]
cc @daxmc99 - what we talked about on our call

**Comment by slimsag** [comment]
Fixed by https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/217
