### ISSUE TITLE
Embeddings deploying with incorrect key in deployment.metadata

### ISSUE THREAD

**Issue by BadLiveware** [sourcegraph/deploy-sourcegraph-helm#287]
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/e8fe42dd6da8a21d4e87e61766a7553e9f025c2b/charts/sourcegraph/templates/embeddings/embeddings.Deployment.yaml#LL14C42-L14C42

This key should be under labels, breaks deploying

**Comment by jac** [comment]
Thanks for reporting this - it slipped through testing.

> breaks deploying

With embeddings enabled in 5.0.4 I receive a couple warnings but the service still successfully deploys.
Can you confirm if it is totally broken for you or if you receive warnings but the service still deploys

Thanks!

**Comment by BadLiveware** [comment]
We run argocd which does validation so for us it doesnt deploy at all

**Comment by jac** [comment]
@BadLiveware there is now a hotfix release 5.0.4-rev.1 which fixes the issue
