### ISSUE TITLE
extraInitContainers needed

### ISSUE THREAD

**Issue by alyssahardy** [sourcegraph/deploy-sourcegraph-helm#384]
I am trying to deploy this helm chart with cloud-sql-proxy as a connector. It is impossible to add it with this helm chart. While there is an extraContainers value, there is no extraInitContainers, so the migrator cannot connect to a cloud-sql-proxy sidecar. Essentially, the cloud-sql-proxy allows easy encrypted connections from a sidecar.

https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#run_the_in_a_sidecar_pattern

**Comment by loujar** [comment]
Kubernetes initContainers can only be scheduled in a [sequential series](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#understanding-init-containers) and not in parallel, therefore the `migrator` initContainer cannot take advantage of the `cloud-sql-proxy` sidecar deployment method.

The recommend workaround is to either deploy `cloud-sql-proxy` as a standalone service alongside the Sourcegraph helm chart, or utilize the [cloud-sql-proxy operator](https://cloud.google.com/sql/docs/postgres/connect-proxy-operator) solution.
