### ISSUE TITLE
Searcher and Symbols use StatefulSets

### ISSUE THREAD

**Issue by jdpleiness** [sourcegraph/deploy-sourcegraph-helm#389]
Release team came across a possible issue in the usage of StatefulSets and VolumeClaims for [Symbols](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/f0d843e574b2735b2b5da49b5a3c9224e5f82dac/charts/sourcegraph/templates/symbols/symbols.StatefulSet.yaml#L136-L145) and [Searcher](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/f0d843e574b2735b2b5da49b5a3c9224e5f82dac/charts/sourcegraph/templates/searcher/searcher.StatefulSet.yaml#L128-L137) services in our Helm charts.

This issue appears to have originated in PR https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/242, however the PR is scant on details around the motivation for the change. 

The PR appears to add `volumeClaimTemplates` and modify the resource kinds from `Deployments` to `StatefulSets`, however the Pod volumes are ephemeral `emptyDir` and do not/will not use the defined `volumeClaimTemplates` (to the best of my understanding at least).

We're looking to get some context on the original issue here and what the intended outcome was for these changes.

**Comment by daxmc99** [comment]
The reason for the change is in the [CHANGELOG](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md?plain=1#L118)

**Comment by daxmc99** [comment]
Even at the time though, I believe this was somewhat controversial. We made this change for a single customer. 
A large number of K8s offerings give tiny amounts of ephemeral storage so this change was to make those "large" storage requests clear. Both of these services use a great deal of cache that scales as services become larger.

**Comment by jdpleiness** [comment]
Thanks @daxmc99, that makes sense. I guess where I'm still confused is it looks as though we are [still using ephemeral storage](https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/242/files#diff-3c90ef87affebe94ebafed82dbac6b70182f405d868838d5a688d768c8be62bdR115-R119) via `emptyDir` and not using the new PVC.

I'm also a little confused as to why this would need to be switched from a Deployment to a StatefulSet. Again, I think I must be missing something here 🤔

**Comment by daxmc99** [comment]
@jdpleiness 
> I'm still confused is it looks as though we are [still using ephemeral storage](https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/242/files#diff-3c90ef87affebe94ebafed82dbac6b70182f405d868838d5a688d768c8be62bdR115-R119) via emptyDir and not using the new PVC.

This seems to be a typo and surprisingly, on cloud, it looks like Kubernetes merges the names and turns it into PVC 🤯 

<details>
<summary>Details</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: symbols
    app.kubernetes.io/component: symbols
    app.kubernetes.io/instance: src-abb935623e5d0740f557
    app.kubernetes.io/name: sourcegraph
    controller-revision-hash: symbols-dc4594b6b
    deploy: sourcegraph
    statefulset.kubernetes.io/pod-name: symbols-0
  name: symbols-0
  namespace: src-c4d017c09a0d9bbb90cc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: symbols
    uid: cc4d510e-b039-4220-aea1-c697798d7a90
  resourceVersion: "175464648"
  uid: 767dd113-1251-4622-98b5-ab0d79d46301
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/machine-family
            operator: In
            values:
            - n2
  containers:
  - env:
    - name: REDIS_CACHE_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: endpoint
          name: redis-cache
    - name: REDIS_STORE_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: endpoint
          name: redis-store
    - name: EXPORT_USAGE_DATA_ENABLED
      value: "true"
    - name: SRC_LOG_FORMAT
      value: json_gcp
    - name: SYMBOLS_CACHE_SIZE_MB
      value: "10800"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: SYMBOLS_CACHE_DIR
      value: /mnt/cache/$(POD_NAME)
    - name: TMPDIR
      value: /mnt/tmp
    - name: OTEL_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(OTEL_AGENT_HOST):4317
    image: index.docker.io/sourcegraph/symbols:5.2.5@sha256:b5e6aad8994e6dfcf827f0a7a6766ac38e5afce79b8ae03461569b458df948f3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: symbols
    ports:
    - containerPort: 3184
      name: http
      protocol: TCP
    - containerPort: 6060
      name: debug
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "6"
        memory: 12Gi
      requests:
        cpu: "2"
        memory: 10Gi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 101
      runAsUser: 100
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /mnt/cache
      name: cache
    - mountPath: /mnt/tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r2jck
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: symbols-0
  nodeName: gke-src-1112a621d0b0-nap-n2-standard--2d7b5d34-px8r
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: gke.io/optimize-utilization-scheduler
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
    runAsUser: 100
  serviceAccount: symbols
  serviceAccountName: symbols
  subdomain: symbols
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: cache-symbols-0
  - emptyDir: {}
    name: tmp
  - name: kube-api-access-r2jck
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  
```

</details>

> why do this?

If you have a deployment with a PVC and you scale from 1 to 2, the second pod will have a volume claim attachment error.

[stackoverflow](https://stackoverflow.com/questions/65797064/how-to-scale-a-kubernetes-deployment-which-uses-a-persistent-volume-claim-to-2-p)

While these services default to only having 1 replica, they are technically horizontally scalable. For larger customers, they may scale these horizontally. 

It is arguable if that actually improves the performance, though, since vertically scaling these resources is usually more effective because they are able to utilize the cache better if all requests go to the same resource. 

I think my preferred solution was to make this togglable in Helm or have Helm take care of creating additional PVCs as the deployment replica counts was increased. 

Overall, this fix was created to answer a single customer's issue without much thought into the larger effects.

**Comment by jdpleiness** [comment]
> This seems to be a typo and surprisingly, on cloud, it looks like Kubernetes merges the names and turns it into PVC 🤯

I'm also 🤯 ...  I would not have expected that. 

>Overall, this fix was created to answer a single customer's issue without much thought into the larger effects. I wouldn't consider this decision something to maintain and think there are better solutions that what we did.

Sounds good. We'll probably come back to this and make some changes in the near future. Generic ephemeral volumes looks promising as you pointed out. 

Thanks for the context @daxmc99, I Appreciate it!
